services:
  streak-stats:
    build:
      context: .
    volumes:
    - ./.env:/var/www/html/.env:ro
    env_file:
    - path: ./.env
    # required for token
      required: true
    ports:
      - "${APP_PORT:-8000}:8000"
